name: On Pull Request (OpenAPI Spec)

on:
  pull_request:
    branches:
      - master
    paths:
      - 'spec/**'

jobs:
  lint:
    uses: ./.github/workflows/job-openapi-lint.yml
    with:
      working-directory: spec
  bundle:
    needs:
      - lint
    uses: ./.github/workflows/job-openapi-bundle.yml
    permissions:
      contents: write
    with:
      working-directory: spec
